/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Observer;

/**
 *
 * @author Mason
 */
public class frmObserver extends javax.swing.JFrame {

    static Weather weather = new Weather();
    WindSpeed wind;
    Pressure pressure;
    /**
     * Creates new form frmObserver
     */
    public frmObserver() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSubPressure = new javax.swing.JButton();
        btnSubWind = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
<<<<<<< HEAD
        lbWins = new javax.swing.JLabel();
        lbLosses = new javax.swing.JLabel();
        lbGameVals = new javax.swing.JLabel();
        lbWinVal = new javax.swing.JLabel();
        lbLossVal = new javax.swing.JLabel();
        btnPittsburgh = new javax.swing.JButton();
        btnPittsburgh1 = new javax.swing.JButton();
        btnPittsburgh2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstTeams = new javax.swing.JList();
        lbLosses1 = new javax.swing.JLabel();
        lbLosses2 = new javax.swing.JLabel();
        lbLosses3 = new javax.swing.JLabel();
        lbOTLVal = new javax.swing.JLabel();
        lbGFVal = new javax.swing.JLabel();
        lbGAVal = new javax.swing.JLabel();
        lbTeamName = new javax.swing.JLabel();
        lbTeamNameTitle = new javax.swing.JLabel();
=======
        tbPressure = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tbWind = new javax.swing.JTextField();
>>>>>>> origin/master

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSubPressure.setText("Subscribe");
        btnSubPressure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubPressureActionPerformed(evt);
            }
        });

<<<<<<< HEAD
        btnPittsburgh1.setText("Minnesota Wild");
        btnPittsburgh1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnPittsburgh1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPittsburgh1ActionPerformed(evt);
            }
        });

        btnPittsburgh2.setText("General Hockey Fan");
        btnPittsburgh2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnPittsburgh2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPittsburgh2ActionPerformed(evt);
            }
        });

        lstTeams.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lstTeams.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstTeamsValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(lstTeams);

        lbLosses1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbLosses1.setText("Overtime Losses:");

        lbLosses2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbLosses2.setText("Goals For");

        lbLosses3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbLosses3.setText("Goals Against");

        lbOTLVal.setText("0");
=======
        btnSubWind.setText("Subscribe");
        btnSubWind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubWindActionPerformed(evt);
            }
        });

        jLabel1.setText("Wind:");
>>>>>>> origin/master

        jLabel2.setText("Pressure:");

        jLabel3.setText("Barometric pressure:");
        jLabel3.setToolTipText("");

<<<<<<< HEAD
        lbTeamName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbTeamName.setText(".");

        lbTeamNameTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbTeamNameTitle.setText("Selected Team:");
=======
        jLabel4.setText("Wind Speed:");
        jLabel4.setToolTipText("");
>>>>>>> origin/master

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
<<<<<<< HEAD
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbGamesPlayed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbLosses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbWins, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbLosses1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbLosses2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbLosses3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbGameVals, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                                    .addComponent(lbWinVal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbLossVal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbOTLVal, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                                    .addComponent(lbGFVal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbGAVal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabel2))
                        .addGap(106, 106, 106))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnPittsburgh2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPittsburgh1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                            .addComponent(btnPittsburgh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbTeamNameTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbTeamName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbTeamNameTitle)
                    .addComponent(btnPittsburgh, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbTeamName)
                    .addComponent(btnPittsburgh1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPittsburgh2, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addGap(12, 12, 12)
=======
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(btnSubWind)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addComponent(tbWind, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnSubPressure)
                                .addComponent(jLabel2))
                            .addGap(41, 41, 41)
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(tbPressure, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
>>>>>>> origin/master
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubPressure)
                    .addComponent(tbPressure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubWind)
                    .addComponent(tbWind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

<<<<<<< HEAD
    private void btnPittsburghActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPittsburghActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPittsburghActionPerformed

    private void btnPittsburgh1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPittsburgh1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPittsburgh1ActionPerformed

    private void btnPittsburgh2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPittsburgh2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPittsburgh2ActionPerformed

    //
    //
    //
    //
    private void lstTeamsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstTeamsValueChanged
            lbTeamName.setText(lstTeams.getSelectedValue().toString());
    }//GEN-LAST:event_lstTeamsValueChanged
=======
    private void btnSubPressureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubPressureActionPerformed
        if(btnSubPressure.getLabel() == "Subscribe"){
            btnSubPressure.setText("Unsubscribe");
            weather.subscribe(pressure);
            return;
        }
        else if(btnSubPressure.getLabel() == "Unsubscribe") {
            btnSubPressure.setText("Subscribe");
            weather.unsubscribe(pressure);
            return;
        }
            
    }//GEN-LAST:event_btnSubPressureActionPerformed

    private void btnSubWindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubWindActionPerformed
        if(btnSubPressure.getLabel() == "Subscribe"){
            btnSubPressure.setText("Unsubscribe");
            weather.subscribe(wind);
            return;
        }
        else if(btnSubPressure.getLabel() == "Unsubscribe") {
            btnSubPressure.setText("Subscribe");
            weather.unsubscribe(wind);
            return;
        }
    }//GEN-LAST:event_btnSubWindActionPerformed
>>>>>>> origin/master

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmObserver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmObserver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmObserver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmObserver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmObserver().setVisible(true);
                weather.run();
            }
        });
    }
    
    public void updateTextFields() {
        for(int i = 0; i <= weather.getList().size()-1;i++) {
            if(weather.getList().get(i).equals(WindSpeed.class))
                tbWind.setText(Integer.toString(weather.getList().get(i).getValue()));
            else if(weather.getList().get(i).equals(Pressure.class))
                tbPressure.setText(Integer.toString(weather.getList().get(i).getValue()));
        } 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
<<<<<<< HEAD
    private javax.swing.JButton btnPittsburgh;
    private javax.swing.JButton btnPittsburgh1;
    private javax.swing.JButton btnPittsburgh2;
=======
    private javax.swing.JButton btnSubPressure;
    private javax.swing.JButton btnSubWind;
    private javax.swing.JLabel jLabel1;
>>>>>>> origin/master
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField tbPressure;
    private javax.swing.JTextField tbWind;
    // End of variables declaration//GEN-END:variables
}
